apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fileserver
  name: fileserver
  namespace: op
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-fs-hdd