kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hadoop-ou-keytab-pvc
  namespace: qa
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: qa-hadoop-ou-keytab-pv
  volumeMode: Filesystem